# Generated by Django 5.1.3 on 2024-11-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='connection',
            name='level',
            field=models.CharField(choices=[('level_1', '1'), ('level_2', '2'), ('level_3', '3')], default='level_1', max_length=10),
        ),
    ]
