# Generated by Django 5.1.3 on 2024-11-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_connection_accepted_alter_connection_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=None, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
