# Generated by Django 5.1.3 on 2024-12-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategory',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
