# Generated by Django 5.1.3 on 2024-12-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_usercategory_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit',
            field=models.FloatField(default=0.0),
        ),
    ]
