# Generated by Django 5.1.3 on 2024-12-10 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0006_offer_task'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='offer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Content.offer'),
        ),
    ]
