# Generated by Django 5.1.3 on 2024-12-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0006_offer_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
