# Generated by Django 5.1.3 on 2024-12-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0007_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
