# Generated by Django 5.1.3 on 2024-12-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0008_alter_task_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('finished', 'finished'), ('canceled_by_author', 'Canceled by author'), ('canceled_buy_responsible', 'Canceled by responsible')], default='ongoing', max_length=50),
        ),
    ]
